package io.github.biglipbob.FMOD;

@SuppressWarnings({"unused", "SpellCheckingInspection"})
public interface FMODConstants {
    int FMOD_OK = 0;
    int FMOD_VERSION = 0x20306;
    int FMOD_BUILDNUMBER = 149358;
    int FMOD_PLUGIN_SDK_VERSION = 110;
    int FMOD_DSP_GETPARAM_VALUESTR_LENGTH = 32;

    int FMOD_DEBUG_LEVEL_NONE = 0;
    int FMOD_DEBUG_LEVEL_ERROR = 0x1;
    int FMOD_DEBUG_LEVEL_WARNING = 0x2;
    int FMOD_DEBUG_LEVEL_LOG = 0x4;
    int FMOD_DEBUG_TYPE_MEMORY = 0x100;
    int FMOD_DEBUG_TYPE_FILE = 0x200;
    int FMOD_DEBUG_TYPE_CODEC = 0x400;
    int FMOD_DEBUG_TYPE_TRACE = 0x800;
    int FMOD_DEBUG_DISPLAY_TIMESTAMPS = 0x10000;
    int FMOD_DEBUG_DISPLAY_LINENUMBERS = 0x20000;
    int FMOD_DEBUG_DISPLAY_THREAD = 0x40000;

    int FMOD_MEMORY_NORMAL = 0;
    int FMOD_MEMORY_STREAM_FILE = 0x1;
    int FMOD_MEMORY_STREAM_DECODE = 0x2;
    int FMOD_MEMORY_SAMPLEDATA = 0x4;
    int FMOD_MEMORY_DSP_BUFFER = 0x8;
    int FMOD_MEMORY_PLUGIN = 0x10;
    int FMOD_MEMORY_PERSISTENT = 0x200000;
    int FMOD_MEMORY_ALL = 0xFFFFFFFF;

    int FMOD_INIT_NORMAL = 0;
    int FMOD_INIT_STREAM_FROM_UPDATE = 0x1;
    int FMOD_INIT_MIX_FROM_UPDATE = 0x2;
    int FMOD_INIT_3D_RIGHTHANDED = 0x4;
    int FMOD_INIT_CLIP_OUTPUT = 0x8;
    int FMOD_INIT_CHANNEL_LOWPASS = 0x100;
    int FMOD_INIT_CHANNEL_DISTANCEFILTER = 0x200;
    int FMOD_INIT_PROFILE_ENABLE = 0x10000;
    int FMOD_INIT_VOL0_BECOMES_VIRTUAL = 0x20000;
    int FMOD_INIT_GEOMETRY_USECLOSEST = 0x40000;
    int FMOD_INIT_PREFER_DOLBY_DOWNMIX = 0x80000;
    int FMOD_INIT_THREAD_UNSAFE = 0x100000;
    int FMOD_INIT_PROFILE_METER_ALL = 0x200000;
    int FMOD_INIT_MEMORY_TRACKING = 0x400000;

    int FMOD_DRIVER_STATE_CONNECTED = 0x1;
    int FMOD_DRIVER_STATE_DEFAULT = 0x2;

    int FMOD_TIMEUNIT_MS = 0x1;
    int FMOD_TIMEUNIT_PCM = 0x2;
    int FMOD_TIMEUNIT_PCMBYTES = 0x4;
    int FMOD_TIMEUNIT_RAWBYTES = 0x8;
    int FMOD_TIMEUNIT_PCMFRACTION = 0x10;
    int FMOD_TIMEUNIT_MODORDER = 0x100;
    int FMOD_TIMEUNIT_MODROW = 0x200;
    int FMOD_TIMEUNIT_MODPATTERN = 0x400;

    int FMOD_SYSTEM_CALLBACK_DEVICELISTCHANGED = 0x1;
    int FMOD_SYSTEM_CALLBACK_DEVICELOST = 0x2;
    int FMOD_SYSTEM_CALLBACK_MEMORYALLOCATIONFAILED = 0x4;
    int FMOD_SYSTEM_CALLBACK_THREADCREATED = 0x8;
    int FMOD_SYSTEM_CALLBACK_BADDSPCONNECTION = 0x10;
    int FMOD_SYSTEM_CALLBACK_PREMIX = 0x20;
    int FMOD_SYSTEM_CALLBACK_POSTMIX = 0x40;
    int FMOD_SYSTEM_CALLBACK_ERROR = 0x80;
    int FMOD_SYSTEM_CALLBACK_THREADDESTROYED = 0x100;
    int FMOD_SYSTEM_CALLBACK_PREUPDATE = 0x200;
    int FMOD_SYSTEM_CALLBACK_POSTUPDATE = 0x400;
    int FMOD_SYSTEM_CALLBACK_RECORDLISTCHANGED = 0x800;
    int FMOD_SYSTEM_CALLBACK_BUFFEREDNOMIX = 0x1000;
    int FMOD_SYSTEM_CALLBACK_DEVICEREINITIALIZE = 0x2000;
    int FMOD_SYSTEM_CALLBACK_OUTPUTUNDERRUN = 0x4000;
    int FMOD_SYSTEM_CALLBACK_RECORDPOSITIONCHANGED = 0x8000;
    int FMOD_SYSTEM_CALLBACK_ALL = 0xFFFFFFFF;

    int FMOD_DEFAULT = 0;
    int FMOD_LOOP_OFF = 0x1;
    int FMOD_LOOP_NORMAL = 0x2;
    int FMOD_LOOP_BIDI = 0x4;
    int FMOD_2D = 0x8;
    int FMOD_3D = 0x10;
    int FMOD_CREATESTREAM = 0x80;
    int FMOD_CREATESAMPLE = 0x100;
    int FMOD_CREATECOMPRESSEDSAMPLE = 0x200;
    int FMOD_OPENUSER = 0x400;
    int FMOD_OPENMEMORY = 0x800;
    int FMOD_OPENMEMORY_POINT = 0x10000000;
    int FMOD_OPENRAW = 0x1000;
    int FMOD_OPENONLY = 0x2000;
    int FMOD_ACCURATETIME = 0x4000;
    int FMOD_MPEGSEARCH = 0x8000;
    int FMOD_NONBLOCKING = 0x10000;
    int FMOD_UNIQUE = 0x20000;
    int FMOD_3D_HEADRELATIVE = 0x40000;
    int FMOD_3D_WORLDRELATIVE = 0x80000;
    int FMOD_3D_INVERSEROLLOFF = 0x100000;
    int FMOD_3D_LINEARROLLOFF = 0x200000;
    int FMOD_3D_LINEARSQUAREROLLOFF = 0x400000;
    int FMOD_3D_INVERSETAPEREDROLLOFF = 0x800000;
    int FMOD_3D_CUSTOMROLLOFF = 0x4000000;
    int FMOD_3D_IGNOREGEOMETRY = 0x40000000;
    int FMOD_IGNORETAGS = 0x2000000;
    int FMOD_LOWMEM = 0x8000000;
    int FMOD_VIRTUAL_PLAYFROMSTART = 0x80000000;

    int FMOD_CHANNELMASK_FRONT_LEFT = 0x1;
    int FMOD_CHANNELMASK_FRONT_RIGHT = 0x2;
    int FMOD_CHANNELMASK_FRONT_CENTER = 0x4;
    int FMOD_CHANNELMASK_LOW_FREQUENCY = 0x8;
    int FMOD_CHANNELMASK_SURROUND_LEFT = 0x10;
    int FMOD_CHANNELMASK_SURROUND_RIGHT = 0x20;
    int FMOD_CHANNELMASK_BACK_LEFT = 0x40;
    int FMOD_CHANNELMASK_BACK_RIGHT = 0x80;
    int FMOD_CHANNELMASK_BACK_CENTER = 0x100;
    int FMOD_CHANNELMASK_MONO = FMOD_CHANNELMASK_FRONT_LEFT;
    int FMOD_CHANNELMASK_STEREO = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT;
    int FMOD_CHANNELMASK_LRC = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER;
    int FMOD_CHANNELMASK_QUAD = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_SURROUND_LEFT | FMOD_CHANNELMASK_SURROUND_RIGHT;
    int FMOD_CHANNELMASK_SURROUND = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER | FMOD_CHANNELMASK_SURROUND_LEFT | FMOD_CHANNELMASK_SURROUND_RIGHT;
    int FMOD_CHANNELMASK_5POINT1 = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER | FMOD_CHANNELMASK_LOW_FREQUENCY | FMOD_CHANNELMASK_SURROUND_LEFT | FMOD_CHANNELMASK_SURROUND_RIGHT;
    int FMOD_CHANNELMASK_5POINT1_REARS = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER | FMOD_CHANNELMASK_LOW_FREQUENCY | FMOD_CHANNELMASK_BACK_LEFT | FMOD_CHANNELMASK_BACK_RIGHT;
    int FMOD_CHANNELMASK_7POINT0 = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER | FMOD_CHANNELMASK_SURROUND_LEFT | FMOD_CHANNELMASK_SURROUND_RIGHT | FMOD_CHANNELMASK_BACK_LEFT | FMOD_CHANNELMASK_BACK_RIGHT;
    int FMOD_CHANNELMASK_7POINT1 = FMOD_CHANNELMASK_FRONT_LEFT | FMOD_CHANNELMASK_FRONT_RIGHT | FMOD_CHANNELMASK_FRONT_CENTER | FMOD_CHANNELMASK_LOW_FREQUENCY | FMOD_CHANNELMASK_SURROUND_LEFT | FMOD_CHANNELMASK_SURROUND_RIGHT | FMOD_CHANNELMASK_BACK_LEFT | FMOD_CHANNELMASK_BACK_RIGHT;

    long FMOD_PORT_INDEX_NONE = 0xFFFFFFFFFFFFFFFFL;

    int FMOD_THREAD_PRIORITY_PLATFORM_MIN = -32 * 1024;
    int FMOD_THREAD_PRIORITY_PLATFORM_MAX = 32 * 1024;
    int FMOD_THREAD_PRIORITY_DEFAULT = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 1;
    int FMOD_THREAD_PRIORITY_LOW = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 2;
    int FMOD_THREAD_PRIORITY_GEOMETRY = FMOD_THREAD_PRIORITY_LOW;
    int FMOD_THREAD_PRIORITY_MEDIUM = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 3;
    int FMOD_THREAD_PRIORITY_PROFILER = FMOD_THREAD_PRIORITY_MEDIUM;
    int FMOD_THREAD_PRIORITY_STUDIO_UPDATE = FMOD_THREAD_PRIORITY_MEDIUM;
    int FMOD_THREAD_PRIORITY_STUDIO_LOAD_BANK = FMOD_THREAD_PRIORITY_MEDIUM;
    int FMOD_THREAD_PRIORITY_STUDIO_LOAD_SAMPLE = FMOD_THREAD_PRIORITY_MEDIUM;
    int FMOD_THREAD_PRIORITY_HIGH = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 4;
    int FMOD_THREAD_PRIORITY_FILE = FMOD_THREAD_PRIORITY_HIGH;
    int FMOD_THREAD_PRIORITY_NONBLOCKING = FMOD_THREAD_PRIORITY_HIGH;
    int FMOD_THREAD_PRIORITY_RECORD = FMOD_THREAD_PRIORITY_HIGH;
    int FMOD_THREAD_PRIORITY_VERY_HIGH = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 5;
    int FMOD_THREAD_PRIORITY_STREAM = FMOD_THREAD_PRIORITY_VERY_HIGH;
    int FMOD_THREAD_PRIORITY_CONVOLUTION1 = FMOD_THREAD_PRIORITY_VERY_HIGH;
    int FMOD_THREAD_PRIORITY_CONVOLUTION2 = FMOD_THREAD_PRIORITY_VERY_HIGH;
    int FMOD_THREAD_PRIORITY_EXTREME = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 6;
    int FMOD_THREAD_PRIORITY_MIXER = FMOD_THREAD_PRIORITY_EXTREME;
    int FMOD_THREAD_PRIORITY_CRITICAL = FMOD_THREAD_PRIORITY_PLATFORM_MIN - 7;
    int FMOD_THREAD_PRIORITY_FEEDER = FMOD_THREAD_PRIORITY_CRITICAL;
    int FMOD_THREAD_STACK_SIZE_DEFAULT = 0;
    int FMOD_THREAD_STACK_SIZE_MIXER = 80 * 1024;
    int FMOD_THREAD_STACK_SIZE_FEEDER = 16 * 1024;
    int FMOD_THREAD_STACK_SIZE_STREAM = 96 * 1024;
    int FMOD_THREAD_STACK_SIZE_FILE = 64 * 1024;
    int FMOD_THREAD_STACK_SIZE_NONBLOCKING = 112 * 1024;
    int FMOD_THREAD_STACK_SIZE_RECORD = 16 * 1024;
    int FMOD_THREAD_STACK_SIZE_GEOMETRY = 48 * 1024;
    int FMOD_THREAD_STACK_SIZE_PROFILER = 128 * 1024;
    int FMOD_THREAD_STACK_SIZE_STUDIO_UPDATE = 96 * 1024;
    int FMOD_THREAD_STACK_SIZE_STUDIO_LOAD_BANK = 96 * 1024;
    int FMOD_THREAD_STACK_SIZE_STUDIO_LOAD_SAMPLE = 96 * 1024;
    int FMOD_THREAD_STACK_SIZE_CONVOLUTION1 = 16 * 1024;
    int FMOD_THREAD_STACK_SIZE_CONVOLUTION2 = 16 * 1024;

    long FMOD_THREAD_AFFINITY_GROUP_DEFAULT = 0x4000000000000000L;
    long FMOD_THREAD_AFFINITY_GROUP_A = 0x4000000000000001L;
    long FMOD_THREAD_AFFINITY_GROUP_B = 0x4000000000000002L;
    long FMOD_THREAD_AFFINITY_GROUP_C = 0x4000000000000003L;

    long FMOD_THREAD_AFFINITY_MIXER = FMOD_THREAD_AFFINITY_GROUP_A;
    long FMOD_THREAD_AFFINITY_FEEDER = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_STREAM = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_FILE = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_NONBLOCKING = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_RECORD = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_GEOMETRY = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_PROFILER = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_STUDIO_UPDATE = FMOD_THREAD_AFFINITY_GROUP_B;
    long FMOD_THREAD_AFFINITY_STUDIO_LOAD_BANK = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_STUDIO_LOAD_SAMPLE = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_CONVOLUTION1 = FMOD_THREAD_AFFINITY_GROUP_C;
    long FMOD_THREAD_AFFINITY_CONVOLUTION2 = FMOD_THREAD_AFFINITY_GROUP_C;

    int FMOD_THREAD_AFFINITY_CORE_ALL = 0;
    int FMOD_THREAD_AFFINITY_CORE_0 = 1;
    int FMOD_THREAD_AFFINITY_CORE_1 = 1 << 1;
    int FMOD_THREAD_AFFINITY_CORE_2 = 1 << 2;
    int FMOD_THREAD_AFFINITY_CORE_3 = 1 << 3;
    int FMOD_THREAD_AFFINITY_CORE_4 = 1 << 4;
    int FMOD_THREAD_AFFINITY_CORE_5 = 1 << 5;
    int FMOD_THREAD_AFFINITY_CORE_6 = 1 << 6;
    int FMOD_THREAD_AFFINITY_CORE_7 = 1 << 7;
    int FMOD_THREAD_AFFINITY_CORE_8 = 1 << 8;
    int FMOD_THREAD_AFFINITY_CORE_9 = 1 << 9;
    int FMOD_THREAD_AFFINITY_CORE_10 = 1 << 10;
    int FMOD_THREAD_AFFINITY_CORE_11 = 1 << 11;
    int FMOD_THREAD_AFFINITY_CORE_12 = 1 << 12;
    int FMOD_THREAD_AFFINITY_CORE_13 = 1 << 13;
    int FMOD_THREAD_AFFINITY_CORE_14 = 1 << 14;
    int FMOD_THREAD_AFFINITY_CORE_15 = 1 << 15;

    float[] FMOD_PRESET_OFF = {1000f, 7f, 11f, 5000f, 100f, 100f, 100f, 250f, 0f, 20f, 96f, -80.0f};
    float[] FMOD_PRESET_GENERIC = {1500f, 7f, 11f, 5000f, 83f, 100f, 100f, 250f, 0f, 14500f, 96f, -8.0f};
    float[] FMOD_PRESET_PADDEDCELL = {170f, 1f, 2f, 5000f, 10f, 100f, 100f, 250f, 0f, 160f, 84f, -7.8f};
    float[] FMOD_PRESET_ROOM = {400f, 2f, 3f, 5000f, 83f, 100f, 100f, 250f, 0f, 6050f, 88f, -9.4f};
    float[] FMOD_PRESET_BATHROOM = {1500f, 7f, 11f, 5000f, 54f, 100f, 60f, 250f, 0f, 2900f, 83f, 0.5f};
    float[] FMOD_PRESET_LIVINGROOM = {500f, 3f, 4f, 5000f, 10f, 100f, 100f, 250f, 0f, 160f, 58f, -19.0f};
    float[] FMOD_PRESET_STONEROOM = {2300f, 12f, 17f, 5000f, 64f, 100f, 100f, 250f, 0f, 7800f, 71f, -8.5f};
    float[] FMOD_PRESET_AUDITORIUM = {4300f, 20f, 30f, 5000f, 59f, 100f, 100f, 250f, 0f, 5850f, 64f, -11.7f};
    float[] FMOD_PRESET_CONCERTHALL = {3900f, 20f, 29f, 5000f, 70f, 100f, 100f, 250f, 0f, 5650f, 80f, -9.8f};
    float[] FMOD_PRESET_CAVE = {2900f, 15f, 22f, 5000f, 100f, 100f, 100f, 250f, 0f, 20000f, 59f, -11.3f};
    float[] FMOD_PRESET_ARENA = {7200f, 20f, 30f, 5000f, 33f, 100f, 100f, 250f, 0f, 4500f, 80f, -9.6f};
    float[] FMOD_PRESET_HANGAR = {10000f, 20f, 30f, 5000f, 23f, 100f, 100f, 250f, 0f, 3400f, 72f, -7.4f};
    float[] FMOD_PRESET_CARPETTEDHALLWAY = {300f, 2f, 30f, 5000f, 10f, 100f, 100f, 250f, 0f, 500f, 56f, -24.0f};
    float[] FMOD_PRESET_HALLWAY = {1500f, 7f, 11f, 5000f, 59f, 100f, 100f, 250f, 0f, 7800f, 87f, -5.5f};
    float[] FMOD_PRESET_STONECORRIDOR = {270f, 13f, 20f, 5000f, 79f, 100f, 100f, 250f, 0f, 9000f, 86f, -6.0f};
    float[] FMOD_PRESET_ALLEY = {1500f, 7f, 11f, 5000f, 86f, 100f, 100f, 250f, 0f, 8300f, 80f, -9.8f};
    float[] FMOD_PRESET_FOREST = {1500f, 162f, 88f, 5000f, 54f, 79f, 100f, 250f, 0f, 760f, 94f, -12.3f};
    float[] FMOD_PRESET_CITY = {1500f, 7f, 11f, 5000f, 67f, 50f, 100f, 250f, 0f, 4050f, 66f, -26.0f};
    float[] FMOD_PRESET_MOUNTAINS = {1500f, 300f, 100f, 5000f, 21f, 27f, 100f, 250f, 0f, 1220f, 82f, -24.0f};
    float[] FMOD_PRESET_QUARRY = {1500f, 61f, 25f, 5000f, 83f, 100f, 100f, 250f, 0f, 3400f, 100f, -5.0f};
    float[] FMOD_PRESET_PLAIN = {1500f, 179f, 100f, 5000f, 50f, 21f, 100f, 250f, 0f, 1670f, 65f, -28.0f};
    float[] FMOD_PRESET_PARKINGLOT = {1700f, 8f, 12f, 5000f, 100f, 100f, 100f, 250f, 0f, 20000f, 56f, -19.5f};
    float[] FMOD_PRESET_SEWERPIPE = {2800f, 14f, 21f, 5000f, 14f, 80f, 60f, 250f, 0f, 3400f, 66f, 1.2f};
    float[] FMOD_PRESET_UNDERWATER = {1500f, 7f, 11f, 5000f, 10f, 100f, 100f, 250f, 0f, 500f, 92f, 7.0f};

    int FMOD_MAX_CHANNEL_WIDTH = 32;
    int FMOD_MAX_SYSTEMS = 8;
    int FMOD_MAX_LISTENERS = 8;
    int FMOD_REVERB_MAXINSTANCES = 4;

    int FMOD_THREAD_TYPE_MIXER = 0;
    int FMOD_THREAD_TYPE_FEEDER = 1;
    int FMOD_THREAD_TYPE_STREAM = 2;
    int FMOD_THREAD_TYPE_FILE = 3;
    int FMOD_THREAD_TYPE_NONBLOCKING = 4;
    int FMOD_THREAD_TYPE_RECORD = 5;
    int FMOD_THREAD_TYPE_GEOMETRY = 6;
    int FMOD_THREAD_TYPE_PROFILER = 7;
    int FMOD_THREAD_TYPE_STUDIO_UPDATE = 8;
    int FMOD_THREAD_TYPE_STUDIO_LOAD_BANK = 9;
    int FMOD_THREAD_TYPE_STUDIO_LOAD_SAMPLE = 10;
    int FMOD_THREAD_TYPE_CONVOLUTION1 = 11;
    int FMOD_THREAD_TYPE_CONVOLUTION2 = 12;

    int FMOD_ERR_BADCOMMAND = 1;
    int FMOD_ERR_CHANNEL_ALLOC = 2;
    int FMOD_ERR_CHANNEL_STOLEN = 3;
    int FMOD_ERR_DMA = 4;
    int FMOD_ERR_DSP_CONNECTION = 5;
    int FMOD_ERR_DSP_DONTPROCESS = 6;
    int FMOD_ERR_DSP_FORMAT = 7;
    int FMOD_ERR_DSP_INUSE = 8;
    int FMOD_ERR_DSP_NOTFOUND = 9;
    int FMOD_ERR_DSP_RESERVED = 10;
    int FMOD_ERR_DSP_SILENCE = 11;
    int FMOD_ERR_DSP_TYPE = 12;
    int FMOD_ERR_FILE_BAD = 13;
    int FMOD_ERR_FILE_COULDNOTSEEK = 14;
    int FMOD_ERR_FILE_DISKEJECTED = 15;
    int FMOD_ERR_FILE_EOF = 16;
    int FMOD_ERR_FILE_ENDOFDATA = 17;
    int FMOD_ERR_FILE_NOTFOUND = 18;
    int FMOD_ERR_FORMAT = 19;
    int FMOD_ERR_HEADER_MISMATCH = 20;
    int FMOD_ERR_HTTP = 21;
    int FMOD_ERR_HTTP_ACCESS = 22;
    int FMOD_ERR_HTTP_PROXY_AUTH = 23;
    int FMOD_ERR_HTTP_SERVER_ERROR = 24;
    int FMOD_ERR_HTTP_TIMEOUT = 25;
    int FMOD_ERR_INITIALIZATION = 26;
    int FMOD_ERR_INITIALIZED = 27;
    int FMOD_ERR_INTERNAL = 28;
    int FMOD_ERR_INVALID_FLOAT = 29;
    int FMOD_ERR_INVALID_HANDLE = 30;
    int FMOD_ERR_INVALID_PARAM = 31;
    int FMOD_ERR_INVALID_POSITION = 32;
    int FMOD_ERR_INVALID_SPEAKER = 33;
    int FMOD_ERR_INVALID_SYNCPOINT = 34;
    int FMOD_ERR_INVALID_THREAD = 35;
    int FMOD_ERR_INVALID_VECTOR = 36;
    int FMOD_ERR_MAXAUDIBLE = 37;
    int FMOD_ERR_MEMORY = 38;
    int FMOD_ERR_MEMORY_CANTPOINT = 39;
    int FMOD_ERR_NEEDS3D = 40;
    int FMOD_ERR_NEEDSHARDWARE = 41;
    int FMOD_ERR_NET_CONNECT = 42;
    int FMOD_ERR_NET_SOCKET_ERROR = 43;
    int FMOD_ERR_NET_URL = 44;
    int FMOD_ERR_NET_WOULD_BLOCK = 45;
    int FMOD_ERR_NOTREADY = 46;
    int FMOD_ERR_OUTPUT_ALLOCATED = 47;
    int FMOD_ERR_OUTPUT_CREATEBUFFER = 48;
    int FMOD_ERR_OUTPUT_DRIVERCALL = 49;
    int FMOD_ERR_OUTPUT_FORMAT = 50;
    int FMOD_ERR_OUTPUT_INIT = 51;
    int FMOD_ERR_OUTPUT_NODRIVERS = 52;
    int FMOD_ERR_PLUGIN = 53;
    int FMOD_ERR_PLUGIN_MISSING = 54;
    int FMOD_ERR_PLUGIN_RESOURCE = 55;
    int FMOD_ERR_PLUGIN_VERSION = 56;
    int FMOD_ERR_RECORD = 57;
    int FMOD_ERR_REVERB_CHANNELGROUP = 58;
    int FMOD_ERR_REVERB_INSTANCE = 59;
    int FMOD_ERR_SUBSOUNDS = 60;
    int FMOD_ERR_SUBSOUND_ALLOCATED = 61;
    int FMOD_ERR_SUBSOUND_CANTMOVE = 62;
    int FMOD_ERR_TAGNOTFOUND = 63;
    int FMOD_ERR_TOOMANYCHANNELS = 64;
    int FMOD_ERR_TRUNCATED = 65;
    int FMOD_ERR_UNIMPLEMENTED = 66;
    int FMOD_ERR_UNINITIALIZED = 67;
    int FMOD_ERR_UNSUPPORTED = 68;
    int FMOD_ERR_VERSION = 69;
    int FMOD_ERR_EVENT_ALREADY_LOADED = 70;
    int FMOD_ERR_EVENT_LIVEUPDATE_BUSY = 71;
    int FMOD_ERR_EVENT_LIVEUPDATE_MISMATCH = 72;
    int FMOD_ERR_EVENT_LIVEUPDATE_TIMEOUT = 73;
    int FMOD_ERR_EVENT_NOTFOUND = 74;
    int FMOD_ERR_STUDIO_UNINITIALIZED = 75;
    int FMOD_ERR_STUDIO_NOT_LOADED = 76;
    int FMOD_ERR_INVALID_STRING = 77;
    int FMOD_ERR_ALREADY_LOCKED = 78;
    int FMOD_ERR_NOT_LOCKED = 79;
    int FMOD_ERR_RECORD_DISCONNECTED = 80;
    int FMOD_ERR_TOOMANYSAMPLES = 81;

    int FMOD_CHANNELCONTROL_CHANNEL = 0;
    int FMOD_CHANNELCONTROL_CHANNELGROUP = 1;

    int FMOD_OUTPUTTYPE_AUTODETECT = 0;
    int FMOD_OUTPUTTYPE_UNKNOWN = 1;
    int FMOD_OUTPUTTYPE_NOSOUND = 2;
    int FMOD_OUTPUTTYPE_WAVWRITER = 3;
    int FMOD_OUTPUTTYPE_NOSOUND_NRT = 4;
    int FMOD_OUTPUTTYPE_WAVWRITER_NRT = 5;
    int FMOD_OUTPUTTYPE_WASAPI = 6;
    int FMOD_OUTPUTTYPE_ASIO = 7;
    int FMOD_OUTPUTTYPE_PULSEAUDIO = 8;
    int FMOD_OUTPUTTYPE_ALSA = 9;
    int FMOD_OUTPUTTYPE_COREAUDIO = 10;
    int FMOD_OUTPUTTYPE_AUDIOTRACK = 11;
    int FMOD_OUTPUTTYPE_OPENSL = 12;
    int FMOD_OUTPUTTYPE_AUDIOOUT = 13;
    int FMOD_OUTPUTTYPE_AUDIO3D = 14;
    int FMOD_OUTPUTTYPE_WEBAUDIO = 15;
    int FMOD_OUTPUTTYPE_NNAUDIO = 16;
    int FMOD_OUTPUTTYPE_WINSONIC = 17;
    int FMOD_OUTPUTTYPE_AAUDIO = 18;
    int FMOD_OUTPUTTYPE_AUDIOWORKLET = 19;
    int FMOD_OUTPUTTYPE_PHASE = 20;
    int FMOD_OUTPUTTYPE_OHAUDIO = 21;

    int FMOD_DEBUG_MODE_TTY = 0;
    int FMOD_DEBUG_MODE_FILE = 1;
    int FMOD_DEBUG_MODE_CALLBACK = 2;

    int FMOD_SPEAKERMODE_DEFAULT = 0;
    int FMOD_SPEAKERMODE_RAW = 1;
    int FMOD_SPEAKERMODE_MONO = 2;
    int FMOD_SPEAKERMODE_STEREO = 3;
    int FMOD_SPEAKERMODE_QUAD = 4;
    int FMOD_SPEAKERMODE_SURROUND = 5;
    int FMOD_SPEAKERMODE_5POINT1 = 6;
    int FMOD_SPEAKERMODE_7POINT1 = 7;
    int FMOD_SPEAKERMODE_7POINT1POINT4 = 8;

    int FMOD_SPEAKER_NONE = -1;
    int FMOD_SPEAKER_FRONT_LEFT = 0;
    int FMOD_SPEAKER_FRONT_RIGHT = 1;
    int FMOD_SPEAKER_FRONT_CENTER = 2;
    int FMOD_SPEAKER_LOW_FREQUENCY = 3;
    int FMOD_SPEAKER_SURROUND_LEFT = 4;
    int FMOD_SPEAKER_SURROUND_RIGHT = 5;
    int FMOD_SPEAKER_BACK_LEFT = 6;
    int FMOD_SPEAKER_BACK_RIGHT = 7;
    int FMOD_SPEAKER_TOP_FRONT_LEFT = 8;
    int FMOD_SPEAKER_TOP_FRONT_RIGHT = 9;
    int FMOD_SPEAKER_TOP_BACK_LEFT = 10;
    int FMOD_SPEAKER_TOP_BACK_RIGHT = 11;

    int FMOD_CHANNELORDER_DEFAULT = 0;
    int FMOD_CHANNELORDER_WAVEFORMAT = 1;
    int FMOD_CHANNELORDER_PROTOOLS = 2;
    int FMOD_CHANNELORDER_ALLMONO = 3;
    int FMOD_CHANNELORDER_ALLSTEREO = 4;
    int FMOD_CHANNELORDER_ALSA = 5;

    int FMOD_PLUGINTYPE_OUTPUT = 0;
    int FMOD_PLUGINTYPE_CODEC = 1;
    int FMOD_PLUGINTYPE_DSP = 2;

    int FMOD_SOUND_TYPE_UNKNOWN = 0;
    int FMOD_SOUND_TYPE_AIFF = 1;
    int FMOD_SOUND_TYPE_ASF = 2;
    int FMOD_SOUND_TYPE_DLS = 3;
    int FMOD_SOUND_TYPE_FLAC = 4;
    int FMOD_SOUND_TYPE_FSB = 5;
    int FMOD_SOUND_TYPE_IT = 6;
    int FMOD_SOUND_TYPE_MIDI = 7;
    int FMOD_SOUND_TYPE_MOD = 8;
    int FMOD_SOUND_TYPE_MPEG = 9;
    int FMOD_SOUND_TYPE_OGGVORBIS = 10;
    int FMOD_SOUND_TYPE_PLAYLIST = 11;
    int FMOD_SOUND_TYPE_RAW = 12;
    int FMOD_SOUND_TYPE_S3M = 13;
    int FMOD_SOUND_TYPE_USER = 14;
    int FMOD_SOUND_TYPE_WAV = 15;
    int FMOD_SOUND_TYPE_XM = 16;
    int FMOD_SOUND_TYPE_XMA = 17;
    int FMOD_SOUND_TYPE_AUDIOQUEUE = 18;
    int FMOD_SOUND_TYPE_AT9 = 19;
    int FMOD_SOUND_TYPE_VORBIS = 20;
    int FMOD_SOUND_TYPE_MEDIA_FOUNDATION = 21;
    int FMOD_SOUND_TYPE_MEDIACODEC = 22;
    int FMOD_SOUND_TYPE_FADPCM = 23;
    int FMOD_SOUND_TYPE_OPUS = 24;

    int FMOD_SOUND_FORMAT_NONE = 0;
    int FMOD_SOUND_FORMAT_PCM8 = 1;
    int FMOD_SOUND_FORMAT_PCM16 = 2;
    int FMOD_SOUND_FORMAT_PCM24 = 3;
    int FMOD_SOUND_FORMAT_PCM32 = 4;
    int FMOD_SOUND_FORMAT_PCMFLOAT = 5;
    int FMOD_SOUND_FORMAT_BITSTREAM = 6;

    int FMOD_OPENSTATE_READY = 0;
    int FMOD_OPENSTATE_LOADING = 1;
    int FMOD_OPENSTATE_ERROR = 2;
    int FMOD_OPENSTATE_CONNECTING = 3;
    int FMOD_OPENSTATE_BUFFERING = 4;
    int FMOD_OPENSTATE_SEEKING = 5;
    int FMOD_OPENSTATE_PLAYING = 6;
    int FMOD_OPENSTATE_SETPOSITION = 7;

    int FMOD_SOUNDGROUP_BEHAVIOR_FAIL = 0;
    int FMOD_SOUNDGROUP_BEHAVIOR_MUTE = 1;
    int FMOD_SOUNDGROUP_BEHAVIOR_STEALLOWEST = 2;

    int FMOD_CHANNELCONTROL_CALLBACK_END = 0;
    int FMOD_CHANNELCONTROL_CALLBACK_VIRTUALVOICE = 1;
    int FMOD_CHANNELCONTROL_CALLBACK_SYNCPOINT = 2;
    int FMOD_CHANNELCONTROL_CALLBACK_OCCLUSION = 3;

    int FMOD_CHANNELCONTROL_DSP_HEAD = -1;
    int FMOD_CHANNELCONTROL_DSP_FADER = -2;
    int FMOD_CHANNELCONTROL_DSP_TAIL = -3;

    int FMOD_ERRORCALLBACK_INSTANCETYPE_NONE = 0;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_SYSTEM = 1;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNEL = 2;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELGROUP = 3;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELCONTROL = 4;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_SOUND = 5;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_SOUNDGROUP = 6;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_DSP = 7;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_DSPCONNECTION = 8;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_GEOMETRY = 9;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_REVERB3D = 10;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_SYSTEM = 11;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTDESCRIPTION = 12;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTINSTANCE = 13;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_PARAMETERINSTANCE = 14;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BUS = 15;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_VCA = 16;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BANK = 17;
    int FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_COMMANDREPLAY = 18;

    int FMOD_DSP_RESAMPLER_DEFAULT = 0;
    int FMOD_DSP_RESAMPLER_NOINTERP = 1;
    int FMOD_DSP_RESAMPLER_LINEAR = 2;
    int FMOD_DSP_RESAMPLER_CUBIC = 3;
    int FMOD_DSP_RESAMPLER_SPLINE = 4;

    int FMOD_DSP_CALLBACK_DATAPARAMETERRELEASE = 0;

    int FMOD_DSPCONNECTION_TYPE_STANDARD = 0;
    int FMOD_DSPCONNECTION_TYPE_SIDECHAIN = 1;
    int FMOD_DSPCONNECTION_TYPE_SEND = 2;
    int FMOD_DSPCONNECTION_TYPE_SEND_SIDECHAIN = 3;

    int FMOD_TAGTYPE_UNKNOWN = 0;
    int FMOD_TAGTYPE_ID3V1 = 1;
    int FMOD_TAGTYPE_ID3V2 = 2;
    int FMOD_TAGTYPE_VORBISCOMMENT = 3;
    int FMOD_TAGTYPE_SHOUTCAST = 4;
    int FMOD_TAGTYPE_ICECAST = 5;
    int FMOD_TAGTYPE_ASF = 6;
    int FMOD_TAGTYPE_MIDI = 7;
    int FMOD_TAGTYPE_PLAYLIST = 8;
    int FMOD_TAGTYPE_FMOD = 9;
    int FMOD_TAGTYPE_USER = 10;

    int FMOD_TAGDATATYPE_BINARY = 0;
    int FMOD_TAGDATATYPE_INT = 1;
    int FMOD_TAGDATATYPE_FLOAT = 2;
    int FMOD_TAGDATATYPE_STRING = 3;
    int FMOD_TAGDATATYPE_STRING_UTF16 = 4;
    int FMOD_TAGDATATYPE_STRING_UTF16BE = 5;
    int FMOD_TAGDATATYPE_STRING_UTF8 = 6;

    int FMOD_PORT_TYPE_MUSIC = 0;
    int FMOD_PORT_TYPE_COPYRIGHT_MUSIC = 1;
    int FMOD_PORT_TYPE_VOICE = 2;
    int FMOD_PORT_TYPE_CONTROLLER = 3;
    int FMOD_PORT_TYPE_PERSONAL = 4;
    int FMOD_PORT_TYPE_VIBRATION = 5;
    int FMOD_PORT_TYPE_AUX = 6;
    int FMOD_PORT_TYPE_PASSTHROUGH = 7;
    int FMOD_PORT_TYPE_VR_VIBRATION = 8;

    int FMOD_DSP_TYPE_UNKNOWN = 0;
    int FMOD_DSP_TYPE_MIXER = 1;
    int FMOD_DSP_TYPE_OSCILLATOR = 2;
    int FMOD_DSP_TYPE_LOWPASS = 3;
    int FMOD_DSP_TYPE_ITLOWPASS = 4;
    int FMOD_DSP_TYPE_HIGHPASS = 5;
    int FMOD_DSP_TYPE_ECHO = 6;
    int FMOD_DSP_TYPE_FADER = 7;
    int FMOD_DSP_TYPE_FLANGE = 8;
    int FMOD_DSP_TYPE_DISTORTION = 9;
    int FMOD_DSP_TYPE_NORMALIZE = 10;
    int FMOD_DSP_TYPE_LIMITER = 11;
    int FMOD_DSP_TYPE_PARAMEQ = 12;
    int FMOD_DSP_TYPE_PITCHSHIFT = 13;
    int FMOD_DSP_TYPE_CHORUS = 14;
    int FMOD_DSP_TYPE_ITECHO = 15;
    int FMOD_DSP_TYPE_COMPRESSOR = 16;
    int FMOD_DSP_TYPE_SFXREVERB = 17;
    int FMOD_DSP_TYPE_LOWPASS_SIMPLE = 18;
    int FMOD_DSP_TYPE_DELAY = 19;
    int FMOD_DSP_TYPE_TREMOLO = 20;
    int FMOD_DSP_TYPE_SEND = 21;
    int FMOD_DSP_TYPE_RETURN = 22;
    int FMOD_DSP_TYPE_HIGHPASS_SIMPLE = 23;
    int FMOD_DSP_TYPE_PAN = 24;
    int FMOD_DSP_TYPE_THREE_EQ = 25;
    int FMOD_DSP_TYPE_FFT = 26;
    int FMOD_DSP_TYPE_LOUDNESS_METER = 27;
    int FMOD_DSP_TYPE_CONVOLUTIONREVERB = 28;
    int FMOD_DSP_TYPE_CHANNELMIX = 29;
    int FMOD_DSP_TYPE_TRANSCEIVER = 30;
    int FMOD_DSP_TYPE_OBJECTPAN = 31;
    int FMOD_DSP_TYPE_MULTIBAND_EQ = 32;
    int FMOD_DSP_TYPE_MULTIBAND_DYNAMICS = 33;

    int FMOD_DSP_OSCILLATOR_TYPE = 0;
    int FMOD_DSP_OSCILLATOR_RATE = 1;

    int FMOD_DSP_LOWPASS_CUTOFF = 0;
    int FMOD_DSP_LOWPASS_RESONANCE = 1;

    int FMOD_DSP_ITLOWPASS_CUTOFF = 0;
    int FMOD_DSP_ITLOWPASS_RESONANCE = 1;

    int FMOD_DSP_HIGHPASS_CUTOFF = 0;
    int FMOD_DSP_HIGHPASS_RESONANCE = 1;

    int FMOD_DSP_ECHO_DELAY = 0;
    int FMOD_DSP_ECHO_FEEDBACK = 1;
    int FMOD_DSP_ECHO_DRYLEVEL = 2;
    int FMOD_DSP_ECHO_WETLEVEL = 3;
    int FMOD_DSP_ECHO_DELAYCHANGEMODE = 4;

    int FMOD_DSP_ECHO_DELAYCHANGEMODE_FADE = 0;
    int FMOD_DSP_ECHO_DELAYCHANGEMODE_LERP = 1;
    int FMOD_DSP_ECHO_DELAYCHANGEMODE_NONE = 2;

    int FMOD_DSP_FADER_GAIN = 0;
    int FMOD_DSP_FADER_OVERALL_GAIN = 1;

    int FMOD_DSP_FLANGE_MIX = 0;
    int FMOD_DSP_FLANGE_DEPTH = 1;
    int FMOD_DSP_FLANGE_RATE = 2;

    int FMOD_DSP_DISTORTION_LEVEL = 0;

    int FMOD_DSP_NORMALIZE_FADETIME = 0;
    int FMOD_DSP_NORMALIZE_THRESHOLD = 1;
    int FMOD_DSP_NORMALIZE_MAXAMP = 2;

    int FMOD_DSP_LIMITER_RELEASETIME = 0;
    int FMOD_DSP_LIMITER_CEILING = 1;
    int FMOD_DSP_LIMITER_MAXIMIZERGAIN = 2;
    int FMOD_DSP_LIMITER_MODE = 3;

    int FMOD_DSP_PARAMEQ_CENTER = 0;
    int FMOD_DSP_PARAMEQ_BANDWIDTH = 1;
    int FMOD_DSP_PARAMEQ_GAIN = 2;

    int FMOD_DSP_MULTIBAND_EQ_A_FILTER = 0;
    int FMOD_DSP_MULTIBAND_EQ_A_FREQUENCY = 1;
    int FMOD_DSP_MULTIBAND_EQ_A_Q = 2;
    int FMOD_DSP_MULTIBAND_EQ_A_GAIN = 3;
    int FMOD_DSP_MULTIBAND_EQ_B_FILTER = 4;
    int FMOD_DSP_MULTIBAND_EQ_B_FREQUENCY = 5;
    int FMOD_DSP_MULTIBAND_EQ_B_Q = 6;
    int FMOD_DSP_MULTIBAND_EQ_B_GAIN = 7;
    int FMOD_DSP_MULTIBAND_EQ_C_FILTER = 8;
    int FMOD_DSP_MULTIBAND_EQ_C_FREQUENCY = 9;
    int FMOD_DSP_MULTIBAND_EQ_C_Q = 10;
    int FMOD_DSP_MULTIBAND_EQ_C_GAIN = 11;
    int FMOD_DSP_MULTIBAND_EQ_D_FILTER = 12;
    int FMOD_DSP_MULTIBAND_EQ_D_FREQUENCY = 13;
    int FMOD_DSP_MULTIBAND_EQ_D_Q = 14;
    int FMOD_DSP_MULTIBAND_EQ_D_GAIN = 15;
    int FMOD_DSP_MULTIBAND_EQ_E_FILTER = 16;
    int FMOD_DSP_MULTIBAND_EQ_E_FREQUENCY = 17;
    int FMOD_DSP_MULTIBAND_EQ_E_Q = 18;
    int FMOD_DSP_MULTIBAND_EQ_E_GAIN = 19;

    int FMOD_DSP_MULTIBAND_EQ_FILTER_DISABLED = 0;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_12DB = 1;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_24DB = 2;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_48DB = 3;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_12DB = 4;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_24DB = 5;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_48DB = 6;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_LOWSHELF = 7;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHSHELF = 8;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_PEAKING = 9;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_BANDPASS = 10;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_NOTCH = 11;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_ALLPASS = 12;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_6DB = 13;
    int FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_6DB = 14;

    int FMOD_DSP_MULTIBAND_DYNAMICS_LOWER_FREQUENCY = 0;
    int FMOD_DSP_MULTIBAND_DYNAMICS_UPPER_FREQUENCY = 1;
    int FMOD_DSP_MULTIBAND_DYNAMICS_LINKED = 2;
    int FMOD_DSP_MULTIBAND_DYNAMICS_USE_SIDECHAIN = 3;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_MODE = 4;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_GAIN = 5;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_THRESHOLD = 6;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_RATIO = 7;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_ATTACK = 8;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_RELEASE = 9;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_GAIN_MAKEUP = 10;
    int FMOD_DSP_MULTIBAND_DYNAMICS_A_RESPONSE_DATA = 11;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_MODE = 12;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_GAIN = 13;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_THRESHOLD = 14;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_RATIO = 15;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_ATTACK = 16;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_RELEASE = 17;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_GAIN_MAKEUP = 18;
    int FMOD_DSP_MULTIBAND_DYNAMICS_B_RESPONSE_DATA = 19;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_MODE = 20;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_GAIN = 21;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_THRESHOLD = 22;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_RATIO = 23;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_ATTACK = 24;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_RELEASE = 25;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_GAIN_MAKEUP = 26;
    int FMOD_DSP_MULTIBAND_DYNAMICS_C_RESPONSE_DATA = 27;

    int FMOD_DSP_MULTIBAND_DYNAMICS_MODE_DISABLED = 0;
    int FMOD_DSP_MULTIBAND_DYNAMICS_MODE_COMPRESS_UP = 1;
    int FMOD_DSP_MULTIBAND_DYNAMICS_MODE_COMPRESS_DOWN = 2;
    int FMOD_DSP_MULTIBAND_DYNAMICS_MODE_EXPAND_UP = 3;
    int FMOD_DSP_MULTIBAND_DYNAMICS_MODE_EXPAND_DOWN = 4;

    int FMOD_DSP_PITCHSHIFT_PITCH = 0;
    int FMOD_DSP_PITCHSHIFT_FFTSIZE = 1;
    int FMOD_DSP_PITCHSHIFT_OVERLAP = 2;
    int FMOD_DSP_PITCHSHIFT_MAXCHANNELS = 3;

    int FMOD_DSP_CHORUS_MIX = 0;
    int FMOD_DSP_CHORUS_RATE = 1;
    int FMOD_DSP_CHORUS_DEPTH = 2;

    int FMOD_DSP_ITECHO_WETDRYMIX = 0;
    int FMOD_DSP_ITECHO_FEEDBACK = 1;
    int FMOD_DSP_ITECHO_LEFTDELAY = 2;
    int FMOD_DSP_ITECHO_RIGHTDELAY = 3;
    int FMOD_DSP_ITECHO_PANDELAY = 4;

    int FMOD_DSP_COMPRESSOR_THRESHOLD = 0;
    int FMOD_DSP_COMPRESSOR_RATIO = 1;
    int FMOD_DSP_COMPRESSOR_ATTACK = 2;
    int FMOD_DSP_COMPRESSOR_RELEASE = 3;
    int FMOD_DSP_COMPRESSOR_GAINMAKEUP = 4;
    int FMOD_DSP_COMPRESSOR_USESIDECHAIN = 5;
    int FMOD_DSP_COMPRESSOR_LINKED = 6;

    int FMOD_DSP_SFXREVERB_DECAYTIME = 0;
    int FMOD_DSP_SFXREVERB_EARLYDELAY = 1;
    int FMOD_DSP_SFXREVERB_LATEDELAY = 2;
    int FMOD_DSP_SFXREVERB_HFREFERENCE = 3;
    int FMOD_DSP_SFXREVERB_HFDECAYRATIO = 4;
    int FMOD_DSP_SFXREVERB_DIFFUSION = 5;
    int FMOD_DSP_SFXREVERB_DENSITY = 6;
    int FMOD_DSP_SFXREVERB_LOWSHELFFREQUENCY = 7;
    int FMOD_DSP_SFXREVERB_LOWSHELFGAIN = 8;
    int FMOD_DSP_SFXREVERB_HIGHCUT = 9;
    int FMOD_DSP_SFXREVERB_EARLYLATEMIX = 10;
    int FMOD_DSP_SFXREVERB_WETLEVEL = 11;
    int FMOD_DSP_SFXREVERB_DRYLEVEL = 12;

    int FMOD_DSP_LOWPASS_SIMPLE_CUTOFF = 0;

    int FMOD_DSP_DELAY_CH0 = 0;
    int FMOD_DSP_DELAY_CH1 = 1;
    int FMOD_DSP_DELAY_CH2 = 2;
    int FMOD_DSP_DELAY_CH3 = 3;
    int FMOD_DSP_DELAY_CH4 = 4;
    int FMOD_DSP_DELAY_CH5 = 5;
    int FMOD_DSP_DELAY_CH6 = 6;
    int FMOD_DSP_DELAY_CH7 = 7;
    int FMOD_DSP_DELAY_CH8 = 8;
    int FMOD_DSP_DELAY_CH9 = 9;
    int FMOD_DSP_DELAY_CH10 = 10;
    int FMOD_DSP_DELAY_CH11 = 11;
    int FMOD_DSP_DELAY_CH12 = 12;
    int FMOD_DSP_DELAY_CH13 = 13;
    int FMOD_DSP_DELAY_CH14 = 14;
    int FMOD_DSP_DELAY_CH15 = 15;
    int FMOD_DSP_DELAY_MAXDELAY = 16;

    int FMOD_DSP_TREMOLO_FREQUENCY = 0;
    int FMOD_DSP_TREMOLO_DEPTH = 1;
    int FMOD_DSP_TREMOLO_SHAPE = 2;
    int FMOD_DSP_TREMOLO_SKEW = 3;
    int FMOD_DSP_TREMOLO_DUTY = 4;
    int FMOD_DSP_TREMOLO_SQUARE = 5;
    int FMOD_DSP_TREMOLO_PHASE = 6;
    int FMOD_DSP_TREMOLO_SPREAD = 7;

    int FMOD_DSP_SEND_RETURNID = 0;
    int FMOD_DSP_SEND_LEVEL = 1;

    int FMOD_DSP_RETURN_ID = 0;
    int FMOD_DSP_RETURN_INPUT_SPEAKER_MODE = 1;

    int FMOD_DSP_HIGHPASS_SIMPLE_CUTOFF = 0;

    int FMOD_DSP_PAN_2D_STEREO_MODE_DISTRIBUTED = 0;
    int FMOD_DSP_PAN_2D_STEREO_MODE_DISCRETE = 1;

    int FMOD_DSP_PAN_MODE_MONO = 0;
    int FMOD_DSP_PAN_MODE_STEREO = 1;
    int FMOD_DSP_PAN_MODE_SURROUND = 2;

    int FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED = 0;
    int FMOD_DSP_PAN_3D_ROLLOFF_LINEAR = 1;
    int FMOD_DSP_PAN_3D_ROLLOFF_INVERSE = 2;
    int FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED = 3;
    int FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM = 4;

    int FMOD_DSP_PAN_3D_EXTENT_MODE_AUTO = 0;
    int FMOD_DSP_PAN_3D_EXTENT_MODE_USER = 1;
    int FMOD_DSP_PAN_3D_EXTENT_MODE_OFF = 2;

    int FMOD_DSP_PAN_MODE = 0;
    int FMOD_DSP_PAN_2D_STEREO_POSITION = 1;
    int FMOD_DSP_PAN_2D_DIRECTION = 2;
    int FMOD_DSP_PAN_2D_EXTENT = 3;
    int FMOD_DSP_PAN_2D_ROTATION = 4;
    int FMOD_DSP_PAN_2D_LFE_LEVEL = 5;
    int FMOD_DSP_PAN_2D_STEREO_MODE = 6;
    int FMOD_DSP_PAN_2D_STEREO_SEPARATION = 7;
    int FMOD_DSP_PAN_2D_STEREO_AXIS = 8;
    int FMOD_DSP_PAN_ENABLED_SPEAKERS = 9;
    int FMOD_DSP_PAN_3D_POSITION = 10;
    int FMOD_DSP_PAN_3D_ROLLOFF = 11;
    int FMOD_DSP_PAN_3D_MIN_DISTANCE = 12;
    int FMOD_DSP_PAN_3D_MAX_DISTANCE = 13;
    int FMOD_DSP_PAN_3D_EXTENT_MODE = 14;
    int FMOD_DSP_PAN_3D_SOUND_SIZE = 15;
    int FMOD_DSP_PAN_3D_MIN_EXTENT = 16;
    int FMOD_DSP_PAN_3D_PAN_BLEND = 17;
    int FMOD_DSP_PAN_LFE_UPMIX_ENABLED = 18;
    int FMOD_DSP_PAN_OVERALL_GAIN = 19;
    int FMOD_DSP_PAN_SURROUND_SPEAKER_MODE = 20;
    int FMOD_DSP_PAN_2D_HEIGHT_BLEND = 21;
    int FMOD_DSP_PAN_ATTENUATION_RANGE = 22;
    int FMOD_DSP_PAN_OVERRIDE_RANGE = 23;

    int FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_12DB = 0;
    int FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_24DB = 1;
    int FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_48DB = 2;

    int FMOD_DSP_THREE_EQ_LOWGAIN = 0;
    int FMOD_DSP_THREE_EQ_MIDGAIN = 1;
    int FMOD_DSP_THREE_EQ_HIGHGAIN = 2;
    int FMOD_DSP_THREE_EQ_LOWCROSSOVER = 3;
    int FMOD_DSP_THREE_EQ_HIGHCROSSOVER = 4;
    int FMOD_DSP_THREE_EQ_CROSSOVERSLOPE = 5;

    int FMOD_DSP_FFT_WINDOW_RECT = 0;
    int FMOD_DSP_FFT_WINDOW_TRIANGLE = 1;
    int FMOD_DSP_FFT_WINDOW_HAMMING = 2;
    int FMOD_DSP_FFT_WINDOW_HANNING = 3;
    int FMOD_DSP_FFT_WINDOW_BLACKMAN = 4;
    int FMOD_DSP_FFT_WINDOW_BLACKMANHARRIS = 5;

    int FMOD_DSP_FFT_DOWNMIX_NONE = 0;
    int FMOD_DSP_FFT_DOWNMIX_MONO = 1;

    int FMOD_DSP_FFT_WINDOWSIZE = 0;
    int FMOD_DSP_FFT_WINDOW = 1;
    int FMOD_DSP_FFT_BAND_START_FREQ = 2;
    int FMOD_DSP_FFT_BAND_STOP_FREQ = 3;
    int FMOD_DSP_FFT_SPECTRUMDATA = 4;
    int FMOD_DSP_FFT_RMS = 5;
    int FMOD_DSP_FFT_SPECTRAL_CENTROID = 6;
    int FMOD_DSP_FFT_IMMEDIATE_MODE = 7;
    int FMOD_DSP_FFT_DOWNMIX = 8;
    int FMOD_DSP_FFT_CHANNEL = 9;

    int FMOD_DSP_LOUDNESS_METER_STATE = 0;
    int FMOD_DSP_LOUDNESS_METER_WEIGHTING = 1;
    int FMOD_DSP_LOUDNESS_METER_INFO = 2;

    int FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED = -3;
    int FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK = -2;
    int FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL = -1;
    int FMOD_DSP_LOUDNESS_METER_STATE_PAUSED = 0;
    int FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING = 1;

    int FMOD_DSP_CONVOLUTION_REVERB_PARAM_IR = 0;
    int FMOD_DSP_CONVOLUTION_REVERB_PARAM_WET = 1;
    int FMOD_DSP_CONVOLUTION_REVERB_PARAM_DRY = 2;
    int FMOD_DSP_CONVOLUTION_REVERB_PARAM_LINKED = 3;

    int FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT = 0;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO = 1;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO = 2;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD = 3;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1 = 4;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1 = 5;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE = 6;
    int FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4 = 7;

    int FMOD_DSP_CHANNELMIX_OUTPUTGROUPING = 0;
    int FMOD_DSP_CHANNELMIX_GAIN_CH0 = 1;
    int FMOD_DSP_CHANNELMIX_GAIN_CH1 = 2;
    int FMOD_DSP_CHANNELMIX_GAIN_CH2 = 3;
    int FMOD_DSP_CHANNELMIX_GAIN_CH3 = 4;
    int FMOD_DSP_CHANNELMIX_GAIN_CH4 = 5;
    int FMOD_DSP_CHANNELMIX_GAIN_CH5 = 6;
    int FMOD_DSP_CHANNELMIX_GAIN_CH6 = 7;
    int FMOD_DSP_CHANNELMIX_GAIN_CH7 = 8;
    int FMOD_DSP_CHANNELMIX_GAIN_CH8 = 9;
    int FMOD_DSP_CHANNELMIX_GAIN_CH9 = 10;
    int FMOD_DSP_CHANNELMIX_GAIN_CH10 = 11;
    int FMOD_DSP_CHANNELMIX_GAIN_CH11 = 12;
    int FMOD_DSP_CHANNELMIX_GAIN_CH12 = 13;
    int FMOD_DSP_CHANNELMIX_GAIN_CH13 = 14;
    int FMOD_DSP_CHANNELMIX_GAIN_CH14 = 15;
    int FMOD_DSP_CHANNELMIX_GAIN_CH15 = 16;
    int FMOD_DSP_CHANNELMIX_GAIN_CH16 = 17;
    int FMOD_DSP_CHANNELMIX_GAIN_CH17 = 18;
    int FMOD_DSP_CHANNELMIX_GAIN_CH18 = 19;
    int FMOD_DSP_CHANNELMIX_GAIN_CH19 = 20;
    int FMOD_DSP_CHANNELMIX_GAIN_CH20 = 21;
    int FMOD_DSP_CHANNELMIX_GAIN_CH21 = 22;
    int FMOD_DSP_CHANNELMIX_GAIN_CH22 = 23;
    int FMOD_DSP_CHANNELMIX_GAIN_CH23 = 24;
    int FMOD_DSP_CHANNELMIX_GAIN_CH24 = 25;
    int FMOD_DSP_CHANNELMIX_GAIN_CH25 = 26;
    int FMOD_DSP_CHANNELMIX_GAIN_CH26 = 27;
    int FMOD_DSP_CHANNELMIX_GAIN_CH27 = 28;
    int FMOD_DSP_CHANNELMIX_GAIN_CH28 = 29;
    int FMOD_DSP_CHANNELMIX_GAIN_CH29 = 30;
    int FMOD_DSP_CHANNELMIX_GAIN_CH30 = 31;
    int FMOD_DSP_CHANNELMIX_GAIN_CH31 = 32;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH0 = 33;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH1 = 34;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH2 = 35;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH3 = 36;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH4 = 37;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH5 = 38;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH6 = 39;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH7 = 40;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH8 = 41;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH9 = 42;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH10 = 43;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH11 = 44;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH12 = 45;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH13 = 46;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH14 = 47;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH15 = 48;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH16 = 49;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH17 = 50;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH18 = 51;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH19 = 52;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH20 = 53;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH21 = 54;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH22 = 55;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH23 = 56;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH24 = 57;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH25 = 58;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH26 = 59;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH27 = 60;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH28 = 61;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH29 = 62;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH30 = 63;
    int FMOD_DSP_CHANNELMIX_OUTPUT_CH31 = 64;

    int FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO = -1;
    int FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO = 0;
    int FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO = 1;
    int FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND = 2;

    int FMOD_DSP_TRANSCEIVER_TRANSMIT = 0;
    int FMOD_DSP_TRANSCEIVER_GAIN = 1;
    int FMOD_DSP_TRANSCEIVER_CHANNEL = 2;
    int FMOD_DSP_TRANSCEIVER_TRANSMITSPEAKERMODE = 3;

    int FMOD_DSP_OBJECTPAN_3D_POSITION = 0;
    int FMOD_DSP_OBJECTPAN_3D_ROLLOFF = 1;
    int FMOD_DSP_OBJECTPAN_3D_MIN_DISTANCE = 2;
    int FMOD_DSP_OBJECTPAN_3D_MAX_DISTANCE = 3;
    int FMOD_DSP_OBJECTPAN_3D_EXTENT_MODE = 4;
    int FMOD_DSP_OBJECTPAN_3D_SOUND_SIZE = 5;
    int FMOD_DSP_OBJECTPAN_3D_MIN_EXTENT = 6;
    int FMOD_DSP_OBJECTPAN_OVERALL_GAIN = 7;
    int FMOD_DSP_OBJECTPAN_OUTPUTGAIN = 8;
    int FMOD_DSP_OBJECTPAN_ATTENUATION_RANGE = 9;
    int FMOD_DSP_OBJECTPAN_OVERRIDE_RANGE = 10;

    int FMOD_DSP_PROCESS_PERFORM = 0;
    int FMOD_DSP_PROCESS_QUERY = 1;

    int FMOD_DSP_PAN_SURROUND_DEFAULT = 0;
    int FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED = 1;

    int FMOD_DSP_PARAMETER_TYPE_FLOAT = 0;
    int FMOD_DSP_PARAMETER_TYPE_INT = 1;
    int FMOD_DSP_PARAMETER_TYPE_BOOL = 2;
    int FMOD_DSP_PARAMETER_TYPE_DATA = 3;

    int FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR = 0;
    int FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO = 1;
    int FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_PIECEWISE_LINEAR = 2;

    int FMOD_DSP_PARAMETER_DATA_TYPE_USER = 0;
    int FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN = -1;
    int FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES = -2;
    int FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN = -3;
    int FMOD_DSP_PARAMETER_DATA_TYPE_FFT = -4;
    int FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI = -5;
    int FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE = -6;
    int FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE = -7;
}


